AllCops:
  TargetRubyVersion: 2.4.1
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'test/test_helper.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'lib/social_networks_api/*'
    - 'lib/tasks/*'
    - 'config/**/*'

AssignmentInCondition:
  Enabled: false

AlignParameters:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Layout/IndentHash:
  EnforcedStyle: consistent

Style/ClassAndModuleChildren:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  Exclude:
    - spec/**/*

Style/BlockComments:
  Enabled: false

Metrics/BlockLength:
  Exclude: 
    - spec/**/*

Documentation:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false
