bot:
  name: VeneraKnifeBot

chat_ids:
  - -1001178408117

chat_params:
  static: 
    start: 'Привет, тут редактируемый текст'
    help: 'Попроси мем или предсказание'
    private: 'Личные сообщения отключены. Пишите в чат https://t.me/membott'
    

  commands:
    help: 
      - /help
      - help
      - помогите
      - помагите

    start: 
      - /start
      - привет
      - прив

    prediction:
      - /prediction
      - предсказание 
      - прогноз
      - предскажи 

    mem: 
      - /mem
      - мем
      - мемас
      - мемчик
      - мемчики
      - мемсы
      - мемасы
      - мемы
      - мемцов
      - мемас
      - мемцова
      - мамасик
