chat_ids:
  - -1001178408117

chat_params:
  -1001178408117:
    hello_message: 'Привет, правила, правила, кто набрал лайки- выиграл.'
    round: 
      duration: 40
      new_round: 'Начался новый раунд длиной в одну минуту'
      finish_round: 'Раунд закончился'

    commands:
      rules: 'Кидай мем, собирай классы, становись королем аськи'
