bot:
  name: VeneraKnifeBot

chat_ids:
  - -1001178408117


chat_params:
  start: 'Привет, тут редактируемый текст'
  help: 'Попроси мем или предсказание'

  commands:
    help: 
      - /help
      - help
      - помогите
      - помагите

    hello: 
      - привет
      - прив
      - /start
    prediction:
      - предсказание 
      - прогноз
      - предскажи 
      - /prediction

    mem: 
      - мем
      - мемас
      - мемчик
      - мемчики
      - мемсы
      - мемасы
      - мемы
      - мемцов
      - мемас
      - мемцова
      - мамасик
      - /mem
