bot:
  name: VeneraKnifeBot

chat_ids:
  - -1001178408117

notifications:
  chats:
    - id: '-1001302807347'
      message: повторяющееся сообщение
      interval: 10


chat_params:
  static: 
    start: 'Привет, тут редактируемый текст'
    help: 'Попроси мем или предсказание'
    private: 'Личные сообщения отключены. Пишите в чат https://t.me/membott'

  buttons:
    share: Поделиться с друзьями
  
  mem:
    after_message: Ну как?

  commands:
    help: 
      - /help
      - help
      - помогите
      - помагите

    start: 
      - /start
      - привет
      - прив

    prediction:
      - /prediction
      - предсказание 
      - прогноз
      - предскажи 

    mem: 
      - /mem
      - мем
      - мемас
      - мемчик
      - мемчики
      - мемсы
      - мемасы
      - мемы
      - мемцов
      - мемас
      - мемцова
      - мамасик
